#!/bin/bash
# Start rhasspy and the required voice command services
MODULES="${MODULES:=convert music timers fumehood forecast tod sprinklers}"
TAG=assistant
DIR="${BASH_SOURCE%/*}"
[[ -d "$DIR" ]] && cd "$DIR"

function do_screen() {
  local cmd="$1"
  shift
  local name=$(basename $cmd .bash)
  screen -q -ls "$name"
  if [[ "$?" -eq 11 ]] ; then
    logger -t $TAG  "screen for $name already running"
    return -1
  else
    logger -t $TAG "running (screen -d -m -S $name $0 $cmd $*)"
    screen -h 500 -d -m -S "$name" "$cmd" $*
    return 0
  fi
}

# start rhasspy and assistants in "screen" sessions
logger -t $TAG "waiting for rhasspy to start up..."
do_screen /usr/bin/rhasspy -p en  

# wait for mqtt service to start
while ! ss -tlnn | grep -q ":1883"; do
  logger -t $TAG "waiting for Rhasspy to start"
  sleep 1
done
logger -t $TAG "Starting services: $MODULES"
for i in $MODULES ; do
  do_screen ./$i.bash
done

exit 0
