#!/bin/bash
# Start rhasspy and the required voice command services
MODULES="convert music timers fumehood forecast"
TAG=assistant
DIR="${BASH_SOURCE%/*}"
[[ -d "$DIR" ]] && cd "$DIR"

function do_screen() {
  local cmd="$1"
  shift
  local name=$(basename $cmd .bash)
  screen -q -ls "$name"
  if [[ "$?" -eq 11 ]] ; then
    logger -t $TAG  "screen for $name already running"
  else
    logger -t $TAG "running (screen -d -m -S $name $0 $cmd $*)"
    screen -h 500 -d -m -S "$name" "$cmd" $*
  fi
}

# start rhasspy and assistants in "screen" sessions
do_screen /usr/bin/rhasspy -p en
sleep 30
for i in $MODULES ; do
  do_screen ./$i.bash
done
logger -t $TAG "Starting services: $MODULES"
