#!/bin/bash
# stop rhasspy and assistants in "screen" sessions
MODULES="convert music timers"
DIR="${BASH_SOURCE%/*}"
[[ -d "$DIR" ]] && cd "$DIR"

for i in $MODULES;  do
  screen -S $i -X quit
done
screen -S rhasspy -X quit
echo "Home assistant stopped"
